datosgobar/portal-andino

- README.md
- deploy/migrate.sh
- docs/index.md
- docs/setup/migration.md
- mkdocs.yml
Script de migracion de andino v1 a v2
> 38 migracio and1 to and2

- docs/index.md
- docs/setup/recommendations.md
- docs/setup/usage.md
Recomendaciones para seguridad y estabilidad
> 35 recommendations

- Dockerfile
- dev.yml
- latest.yml
Arreglo el envío de mail.
fixes#16
https://github.com/datosgobar/portal-base/pull/24
> Fix emails

- vendor/ckan_2.5.3-trusty_amd64.deb
> Saco .deb innecesario

- dev.yml
> Evito tomar el puerto 25

- Dockerfile
refs datosgobar/portal-andino#77
> Actualizo versión del theme y de portal-base

- Dockerfile
- latest.yml
Contiene el fix para datosgobar/portal-base#41
> Actualizo versión de portal-base

- Dockerfile
- dev.sh
> 73 metadata campos

- Dockerfile
- deploy/upload.sh
Actualizo la version del portal base y el theme
> Release 2.3.0 beta3

- docs/setup/usage.md
> Actualizo documentación para la configuración del servidor SMTP.

- dev.sh
- docs/developers/maintenance.md
Documento el parámetro adicional
> Agrego parámetro al comando

- docs/developers/maintenance.md
Agrego la configuracion para usar la configuracion interna entre nginx y andino
para la cache extendida
Closes #139
> Actualizo la documentacion

- install/install.py
- install/update.py
> Se actualiza el ckan.site_url al instalar o actualizar andino

- docs/developers/maintenance.md
> Documentación para la sección de Google Dataset Search

- docs/developers/maintenance.md
> Actualizo documentación para incluir sección de comandos de datapusher

- install/install.py
- install/update.py
> Mejoro la forma de buscar y reemplazar el campo ckan.site_url

- docs/developers/maintenance.md
> Explicación sobre la importancia del usuario admin de CKAN

- Dockerfile
- docs/developers/update.md
Documentación para datosgobar/portal-andino-theme#364.
> Theme 364 descargar recursos editados con ckan command

- docs/developers/install.md
> Menciono el problema con Datapusher usando como hostname 'localhost'

- docs/developers/maintenance.md
- docs/developers/update.md
Mergear después de https://github.com/datosgobar/portal-base/pull/92.
Closes https://github.com/datosgobar/portal-andino/issues/225.
> 225 correcciones uso json licencias

- install/update.py
> Si no hay site_host al actualizar, obligo al usuario a ingresarlo

- tests/configurations/security/tests_ckanext_security.py
Mergear una vez rehecho el tag 0.10.28 de portal-base.
> Tests para comprobar que no haya errores activando ckanext-security

- docs/developers/maintenance.md
- docs/quickstart.md
> Documentación para embeber recursos

- docs/developers/install.md
- docs/developers/update.md
> Menciono en la documentación problemas al usar localhost como nombre de dominio

- install/installation_manager.py
- install/update.py
> Evito correr scripts al deployear mientras el contenedor aún se está reiniciando

- Dockerfile
- install/install.py
- install/installation_manager.py
- install/update.py
Closes https://github.com/datosgobar/portal-base/issues/102.
> Actualizo instalación y actualización para aplicar configuraciones de ckanext-security

- docs/developers/install.md
> Actualizo versiones de docker y docker-compose mínimas

- install/install.py
- install/update.py
> Fix instalación de Andino buscando el site_url

- docs/quickstart.md
> Especifico en la documentación las versiones compatibles de browsers

- docs/developers/maintenance.md
> Actualizo scripts de backup restore

- install/installation_manager.py
> Cambio función de ping a Nginx para que corte si el status code es distinto a 000

- docs/developers/maintenance.md
> Documentar xloader
